#!/usr/bin/env python3
"""Build the synthetic sample clip that ships with this repo.

The committed `sample-16x9.mp4` was produced by this script. You do not need to run
it — it exists so the sample is reproducible and so you can see that nothing in this
repo is real footage of a real person.

What it makes: a 16:9 slate with a per-second timecode (so you can read straight off
the frame which second of the source landed where in the cut), and a narration track
generated by the operating system's text-to-speech. The narration is deliberately
badly structured — it opens on wind-up, buries the hook, and contains a restart — so
the editing method in `agent/` has something to actually do.

    python3 sample/make_sample.py

Requires: ffmpeg, Pillow, and a text-to-speech binary (`say` on macOS, `espeak-ng`
elsewhere). Without TTS it still builds a silent clip, but transcription will have
nothing to transcribe.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent

W, H, FPS = 1280, 720, 30
BG = (18, 20, 23)
INK = (232, 234, 237)
DIM = (139, 146, 156)
ACCENT = (79, 142, 247)
RULE = (42, 47, 54)

# `[[slnc N]]` is a macOS `say` command for an N-millisecond pause. espeak-ng ignores
# them harmlessly, so the same script drives both; the espeak version just runs tighter.
NARRATION = (
    "[[slnc 400]]Okay. Um. Hey everyone, so, today I wanted to talk about something. "
    "[[slnc 900]]Why does every edit take three hours when the talking part took "
    "ninety seconds? [[slnc 700]]Because the machine is doing the part you should be "
    "judging, and you are doing the part the machine should be running. [[slnc 800]]"
    "The fix is to write down. [[slnc 600]]Sorry. [[slnc 700]]The fix is to write the "
    "decision down once, in one file. [[slnc 700]]Then the render is just arithmetic. "
    "[[slnc 900]]That's it.[[slnc 500]]"
)


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True, capture_output=True)


def font(size: int):
    from PIL import ImageFont

    for candidate in (
        "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/TTF/DejaVuSans.ttf",
    ):
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default(size=size)  # Pillow >= 10.1


def make_narration(dest: Path) -> float:
    """Write a narration track. Returns its duration in seconds, 0.0 if no TTS."""
    if shutil.which("say"):
        script = dest.with_suffix(".txt")
        script.write_text(NARRATION)
        run(["say", "-v", "Daniel", "-r", "178", "-f", str(script), "-o", str(dest)])
        script.unlink()
    elif shutil.which("espeak-ng"):
        run(["espeak-ng", "-s", "150", "-w", str(dest), NARRATION])
    else:
        print("no `say` or `espeak-ng` found — building a silent clip", file=sys.stderr)
        return 0.0

    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nw=1:nk=1", str(dest)],
        check=True, capture_output=True, text=True,
    )
    return float(probe.stdout.strip())


def make_frames(into: Path, seconds: int) -> None:
    from PIL import Image, ImageDraw

    f_title, f_sub, f_code = font(54), font(24), font(64)
    for s in range(seconds):
        img = Image.new("RGB", (W, H), BG)
        d = ImageDraw.Draw(img)

        d.text((W / 2, 250), "SYNTHETIC TAKE A", fill=INK, font=f_title, anchor="mm")
        d.text((W / 2, 306), "landscape-on-black sample clip - not real footage",
               fill=DIM, font=f_sub, anchor="mm")

        d.rectangle((0, 380, W, 383), fill=RULE)
        head = (s + 1) / seconds * W
        d.rectangle((max(0, head - 120), 380, head, 383), fill=ACCENT)

        d.text((W / 2, 470), f"{s // 60:02d}:{s % 60:02d}",
               fill=ACCENT, font=f_code, anchor="mm")

        img.save(into / f"f{s:05d}.png")


def main() -> int:
    out = HERE / "sample-16x9.mp4"
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        audio = tmp / "narration.aiff"
        duration = make_narration(audio)
        seconds = int(duration) + 1 if duration else 20

        frames = tmp / "frames"
        frames.mkdir()
        make_frames(frames, seconds)

        cmd = [
            "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
            # one PNG per second of source, resampled up to FPS
            "-framerate", "1", "-i", str(frames / "f%05d.png"),
        ]
        if duration:
            cmd += ["-i", str(audio)]
        cmd += [
            "-vf", f"fps={FPS},format=yuv420p",
            "-c:v", "libx264", "-preset", "veryslow", "-crf", "30",
            "-pix_fmt", "yuv420p",
        ]
        if duration:
            cmd += ["-c:a", "aac", "-b:a", "64k", "-ac", "1", "-ar", "44100",
                    "-t", f"{duration:.3f}"]
        cmd += ["-movflags", "+faststart", str(out)]
        run(cmd)

    size_kb = out.stat().st_size / 1024
    print(f"wrote {out.name}  ({size_kb:.0f} KB, {seconds}s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
